site_name: DocTools

theme:
  name: material
  features:
    - instant
    - tabs
  language: en
  direction: ltr
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search 
  - awesome-pages
  
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - meta
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - attr_list
